### ISSUE TITLE
Vulnerability:  Use of HTTP exposes keys to eavesdropping.  Use HTTPS!

### ISSUE THREAD

**Issue by JoNilsson** [mbroton/chatgpt-api#1]
This software uses standard HTTP to send requests in plain text, and this could potentially expose the session key that is being used to authenticate the user session.  This is irresponsible. 

HTTP could expose the user's session to potential attackers, who could then use the session key to gain unauthorized access to the user's GPT API access account. 

Use HTTPS!

**Comment by mbroton** [comment]
Hi! Thanks for reporting your concerns.
Can you give some more details at which moment HTTP that is not secured is used?
It would be nice to have a reference point.
App is sending requests only to 2 endpoints, which are over HTTPS, as far as I'm aware.
