### ISSUE TITLE
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

### ISSUE THREAD

**Issue by d-dutchview** [mbroton/chatgpt-api#17]
-chatgpt setup

  File "/Users/USER/.local/share/virtualenvs/seized-dj-l9D8r0wf/lib/python3.8/site-packages/chatgpt/payloads.py", line 5, in <module>
    message: str, id_: str, conv_id: str | None, parent_msg_id: str | None
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

MacOs / python3.8

**Comment by Shuangcheng-Ni** [comment]
For compatibility, it is better to use `typing.Union` instead of `|` in annotations.

**Comment by mbroton** [comment]
I agree.
I've started developing `chatgpt-api` without intent to share, so I didn't care about compatibility.
But now, it's something that could be changed. I'll probably fix it by using `typing` instead of `annotations`.
Thanks for pointing it out @Shuangcheng-Ni.

**Comment by mbroton** [comment]
It's done: https://github.com/mbroton/chatgpt-api/pull/21
But before I can release a new version, I need to take care of that issue: https://github.com/mbroton/chatgpt-api/issues/18
