### ISSUE TITLE
403 Forbidden error

### ISSUE THREAD

**Issue by frankwalter1301** [mbroton/chatgpt-api#2]
I'm getting this error on chatgpt start even though I correctly set up the authentication token.

**Comment by frankwalter1301** [comment]
okay it is just that you need to set up a useragent, they started blocking libraries.

**Comment by mbroton** [comment]
Hi! I did just notice that indeed they've started to check user agent.
Expect fix in an hour or so (v0.1.2). Thanks for reporting the issue!

**Comment by mbroton** [comment]
Version [v0.1.2](https://github.com/mbroton/chatgpt-api/releases/tag/v0.1.2) fixes this issue and it just has been released.
You can upgrade your `chatgpt-api` version by the command:
```
pip install chatgpt-api --upgrade
```
Please let me know if you still have any problems.

**Comment by frankwalter1301** [comment]
Everything is good!

**Comment by adoreblvnk** [comment]
403 error reoccurs again with the latest version. just a heads up.

**Comment by mbroton** [comment]
@adoreblvnk See #18
