### ISSUE TITLE
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

### ISSUE THREAD

**Issue by sudarsun** [mbroton/chatgpt-api#23]
While running "chatgpt setup" from the command line, the following error is reported by Python 3.8 / Ubuntu 20.04.5
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

upon replacing the multiple types "str | None" with Union[str, None], the error goes away.  The replacement has to be done at chatgpt/{api, cli, payloads}.py

**Comment by rvjenya** [comment]
Any solutions?

**Comment by mbroton** [comment]
Hi! It's a duplicate of #22

**Comment by sudarsun** [comment]
The error goes away after replacing the multiple types "str | None" with Union[str, None]. 
The replacement has to be done at chatgpt/{api, cli, payloads}.py
