### ISSUE TITLE
Small Mistake in Usage Examples in Readme.md

### ISSUE THREAD

**Issue by jmanzitti** [mbroton/chatgpt-api#4]
Hi,

Just trying this out, so I might be mistaken, but I think in the examples, where it calls **ChatGPT()**, the argument should be **session_token**, not **session_key**.

`ChatGPT(session_key="your-session-key")`

Thank you for your work on this project!

**Comment by mbroton** [comment]
Hi @jmanzitti!

Yes, you're right, it is a mistake.
Small, but really important, because it could be discouraging for people that want to use `chatgpt-api`.
I fixed it.

Thank you for reporting it! I really appreciate it :)
